import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Sample IC Memo | NeuFin",
  description: "Anonymous investment committee memo generated by NeuFin's agent swarm.",
};

const actions = [
  "Trim single-name concentration above 18% before adding new cyclicals.",
  "Use VN-Index and S&P 500 stress paths as separate benchmark lenses.",
  "Rebalance factor exposure toward cash-flow quality until volatility normalizes.",
];

export default function SampleIcMemoPage() {
  return (
    <main className="min-h-screen bg-white text-[#0F172A]">
      <section className="mx-auto grid max-w-6xl gap-10 px-6 py-12 lg:grid-cols-[1.1fr_0.9fr] lg:items-start">
        <div>
          <p className="text-xs font-bold uppercase tracking-[0.18em] text-[#0369A1]">
            Anonymous sample
          </p>
          <h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-5xl">
            Investment Committee Memo
          </h1>
          <p className="mt-5 max-w-2xl text-lg leading-8 text-[#475569]">
            A regime-aware committee brief with risk posture, position-level actions,
            alpha opportunities, and source attribution.
          </p>
          <div className="mt-8 grid gap-3 sm:grid-cols-3">
            {[
              ["Regime", "Risk-Off"],
              ["Confidence", "78%"],
              ["Benchmark", "VN-Index / S&P 500"],
            ].map(([label, value]) => (
              <div key={label} className="rounded-lg border border-[#CBD5E1] bg-[#F8FAFC] p-4">
                <p className="text-xs font-semibold uppercase tracking-[0.14em] text-[#64748B]">
                  {label}
                </p>
                <p className="mt-2 text-xl font-bold text-[#0F172A]">{value}</p>
              </div>
            ))}
          </div>
        </div>
        <Image
          src="/graphics/ic-report-preview.png"
          width={720}
          height={520}
          alt="Sample IC memo preview"
          className="rounded-lg border border-[#CBD5E1] bg-[#F8FAFC] object-cover"
          priority
        />
      </section>

      <section className="border-y border-[#E2E8F0] bg-[#F8FAFC]">
        <div className="mx-auto max-w-6xl px-6 py-10">
          <h2 className="text-2xl font-bold">Committee Decision</h2>
          <p className="mt-4 max-w-3xl text-base leading-8 text-[#334155]">
            Hold the core allocation, defer incremental beta, and rotate marginal
            capital toward quality balance sheets until drawdown pressure eases.
          </p>
          <div className="mt-8 grid gap-4 md:grid-cols-3">
            {actions.map((action) => (
              <div key={action} className="rounded-lg border border-[#CBD5E1] bg-white p-5">
                <p className="text-sm leading-7 text-[#334155]">{action}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-6 py-12">
        <h2 className="text-2xl font-bold">Agent Notes</h2>
        <div className="mt-6 grid gap-4 md:grid-cols-2">
          <div className="rounded-lg border border-[#CBD5E1] p-5">
            <p className="font-semibold">Risk Sentinel</p>
            <p className="mt-2 text-sm leading-7 text-[#475569]">
              Concentration is the primary live risk. Stress testing shows that
              high-beta financial exposure drives most downside variance.
            </p>
          </div>
          <div className="rounded-lg border border-[#CBD5E1] p-5">
            <p className="font-semibold">Alpha Scout</p>
            <p className="mt-2 text-sm leading-7 text-[#475569]">
              The opportunity set favors local-sector rotation and dividend quality
              over broad index beta.
            </p>
          </div>
        </div>
        <Link
          href="/upload"
          className="mt-10 inline-flex rounded-lg bg-[#0369A1] px-5 py-3 text-sm font-semibold text-white hover:bg-[#075985]"
        >
          Analyze free →
        </Link>
      </section>
    </main>
  );
}
