import type { Metadata } from 'next'
import Link from 'next/link'
import ReactMarkdown from 'react-markdown'

type RelatedNote = {
  id: string
  slug: string
  title: string
  note_type: string
}

type BlogNote = {
  id: string
  slug: string
  title: string
  executive_summary: string
  content: string
  note_type: string
  confidence_score?: number
  created_at: string
  read_time_minutes: number
  asset_tickers: string[]
  meta_description: string
  related_notes: RelatedNote[]
}

function resolveBase() {
  const raw = process.env.NEXT_PUBLIC_APP_URL?.trim()
  if (raw) return raw.startsWith('http') ? raw : `https://${raw}`
  const vercel = process.env.VERCEL_URL?.trim()
  if (vercel) return `https://${vercel}`
  return 'http://localhost:3000'
}

async function fetchResearchNote(slug: string): Promise<BlogNote | null> {
  try {
    const base = resolveBase().replace(/\/$/, '')
    const res = await fetch(`${base}/api/research/blog/${encodeURIComponent(slug)}`, {
      next: { revalidate: 300 },
      cache: 'force-cache',
    })
    if (!res.ok) return null
    return (await res.json()) as BlogNote
  } catch {
    return null
  }
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const note = await fetchResearchNote(slug)
  if (!note) return { title: 'NeuFin Research' }
  return {
    title: `${note.title} | NeuFin Research`,
    description: note.meta_description,
    openGraph: {
      title: note.title,
      description: note.meta_description,
      type: 'article',
      publishedTime: note.created_at,
      authors: ['NeuFin AI Research Team'],
      tags: note.asset_tickers,
    },
  }
}

export default async function ResearchArticlePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const note = await fetchResearchNote(slug)
  if (!note) {
    return (
      <div className="min-h-screen bg-background px-6 py-20 text-foreground">
        <div className="mx-auto max-w-4xl">
          <p className="text-muted-foreground">Research note not found.</p>
        </div>
      </div>
    )
  }

  const keyInsights = note.executive_summary
    .split('.')
    .map((s) => s.trim())
    .filter(Boolean)
    .slice(0, 3)

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto grid max-w-6xl grid-cols-1 gap-8 px-6 py-12 lg:grid-cols-[minmax(0,1fr)_300px]">
        <article>
          <div className="mb-6 text-sm text-muted-foreground">
            <Link href="/research" className="hover:text-foreground">
              Research
            </Link>{' '}
            → <span>{note.note_type.replace(/_/g, ' ')}</span> → <span className="text-foreground">{note.title}</span>
          </div>

          <header className="mb-8">
            <h1 className="text-3xl font-bold leading-tight">{note.title}</h1>
            <div className="mt-3 flex flex-wrap items-center gap-3 text-[11px] font-mono text-muted-foreground">
              <span>{new Date(note.created_at).toLocaleString('en-SG', { dateStyle: 'medium', timeStyle: 'short' })}</span>
              <span>{Math.round((note.confidence_score ?? 0) * 100)}% confidence</span>
              <span>{note.read_time_minutes} min read</span>
            </div>
          </header>

          <div className="prose prose-invert max-w-none prose-p:text-muted-foreground prose-headings:text-foreground">
            <ReactMarkdown>{note.content || note.executive_summary}</ReactMarkdown>
          </div>

          <div className="mt-10 rounded-xl border border-primary/30 bg-primary/10 p-6 text-center">
            <p className="text-sm text-muted-foreground">
              This analysis was generated by NeuFin&apos;s 7-agent swarm. See how these insights apply to YOUR portfolio.
            </p>
            <Link
              href="/upload"
              className="mt-4 inline-block rounded-lg bg-primary px-6 py-3 text-sm font-medium text-primary-foreground"
            >
              Analyze My Portfolio Free
            </Link>
          </div>
        </article>

        <aside className="space-y-4 lg:sticky lg:top-20 lg:self-start">
          <div className="rounded-xl border border-border bg-surface p-4">
            <h3 className="mb-2 text-xs font-mono uppercase tracking-widest text-muted-foreground">Key Insights</h3>
            <ul className="space-y-2 text-sm text-muted-foreground">
              {keyInsights.map((k) => (
                <li key={k}>• {k}</li>
              ))}
            </ul>
          </div>

          <div className="rounded-xl border border-border bg-surface p-4">
            <h3 className="mb-2 text-xs font-mono uppercase tracking-widest text-muted-foreground">Asset Mentions</h3>
            <div className="flex flex-wrap gap-2">
              {note.asset_tickers.map((t) => (
                <span key={t} className="rounded-full border border-primary/30 bg-primary/10 px-2 py-0.5 font-mono text-[11px] text-primary">
                  {t}
                </span>
              ))}
            </div>
          </div>

          <div className="rounded-xl border border-border bg-surface p-4">
            <h3 className="mb-2 text-xs font-mono uppercase tracking-widest text-muted-foreground">Related Research</h3>
            <div className="space-y-2">
              {note.related_notes.map((r) => (
                <Link key={r.id} href={`/research/${r.slug}`} className="block text-sm text-foreground hover:text-primary">
                  {r.title}
                </Link>
              ))}
            </div>
          </div>

          <Link
            href="/upload"
            className="block rounded-xl border border-primary/30 bg-primary/10 p-4 text-center text-sm text-primary"
          >
            Analyze Your Portfolio
          </Link>
        </aside>
      </div>
    </div>
  )
}

