[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[deploy]
# We use sh -c to ensure the shell expands the $PORT variable into an integer
startCommand = "sh -c 'uvicorn main:app --host 0.0.0.0 --port $PORT'"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"