import type { Metadata } from "next";
import { ResearchSubscribeForm } from "@/components/research/ResearchSubscribeForm";
import { ResearchNotesList } from "@/components/research/ResearchNotesList";

export const metadata: Metadata = {
  title: "NeuFin Research | Macro & regime intelligence",
  description:
    "Institutional-grade research notes on market regimes, sectors, and risk — generated by NeuFin synthesis agents.",
};

type ResearchNoteRow = {
  id: string;
  title: string;
  executive_summary: string;
  note_type: string;
  regime?: string | null;
  confidence_score?: number | null;
  generated_at?: string;
};

type RegimePayload = {
  current?: {
    name?: string;
    regime?: string;
    confidence?: number;
    confidence_pct?: number;
    last_updated?: string;
    started_at?: string;
  };
  generated_at?: string;
};

function resolveBase() {
  const raw = process.env.NEXT_PUBLIC_APP_URL?.trim();
  if (raw) return raw.startsWith("http") ? raw : `https://${raw}`;
  const vercel = process.env.VERCEL_URL?.trim();
  if (vercel) return `https://${vercel}`;
  return "http://localhost:3000";
}

function regimePillLabel(r: string | null | undefined) {
  if (!r) return "Neutral";
  const m: Record<string, string> = {
    risk_on: "Risk-On",
    risk_off: "Risk-Off",
    neutral: "Neutral",
    stagflation: "Stagflation",
    recovery: "Recovery",
    recession: "Recession",
  };
  const k = r.toLowerCase().replace(/\s+/g, "_");
  return m[k] || r.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
}

async function fetchNotes(): Promise<ResearchNoteRow[]> {
  try {
    const base = resolveBase().replace(/\/$/, "");
    const res = await fetch(`${base}/api/research/notes?per_page=20&page=1`, {
      next: { revalidate: 120 },
    });
    if (!res.ok) return [];
    const data = (await res.json()) as { notes?: ResearchNoteRow[] };
    return Array.isArray(data.notes) ? data.notes : [];
  } catch {
    return [];
  }
}

async function fetchRegime(): Promise<RegimePayload | null> {
  try {
    const base = resolveBase().replace(/\/$/, "");
    const res = await fetch(`${base}/api/research/regime`, {
      next: { revalidate: 60 },
    });
    if (!res.ok) return null;
    return (await res.json()) as RegimePayload;
  } catch {
    return null;
  }
}

export default async function ResearchPage() {
  const [notes, regime] = await Promise.all([fetchNotes(), fetchRegime()]);

  const current = regime?.current as
    | { regime?: string; confidence?: number; started_at?: string | null }
    | undefined;
  const regimeName = regimePillLabel(current?.regime);
  const confRaw = current?.confidence;
  const confPct =
    typeof confRaw === "number"
      ? confRaw <= 1
        ? Math.round(confRaw * 100)
        : Math.round(confRaw)
      : null;
  const lastUpdated = current?.started_at || regime?.generated_at || null;

  const oldestInFeed = notes.length
    ? notes[notes.length - 1]?.generated_at
    : null;
  const trackingSince = oldestInFeed
    ? new Date(oldestInFeed).toLocaleDateString("en-SG", {
        dateStyle: "medium",
      })
    : null;

  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="mx-auto max-w-6xl px-6 py-section">
        <header className="mb-10">
          <p className="mb-2 font-mono text-sm uppercase tracking-widest text-primary">
            NeuFin research hub
          </p>
          <h1 className="text-3xl font-bold leading-tight md:text-4xl">
            Institutional research &amp; regime intelligence
          </h1>
          <p className="mt-3 max-w-2xl text-muted-foreground">
            Live notes from NeuFin&apos;s synthesis stack — macro, sectors, and
            risk — updated as markets evolve.
          </p>
        </header>

        <div className="grid grid-cols-1 gap-10 lg:grid-cols-[3fr_2fr]">
          <ResearchNotesList notes={notes} />

          <aside className="space-y-6 lg:sticky lg:top-24 lg:self-start">
            <div className="rounded-xl border border-border/60 bg-surface/40 p-5">
              <h3 className="text-sm font-semibold text-foreground">
                Current regime
              </h3>
              <p className="mt-2 text-2xl font-bold capitalize text-foreground">
                {regimeName}
              </p>
              {confPct != null && (
                <p className="mt-1 text-sm text-muted-foreground">
                  Confidence: {confPct}%
                </p>
              )}
              {lastUpdated && (
                <p className="mt-2 text-xs text-muted-foreground">
                  Last updated:{" "}
                  {new Date(lastUpdated).toLocaleString("en-SG", {
                    dateStyle: "medium",
                    timeStyle: "short",
                  })}
                </p>
              )}
            </div>

            <div className="rounded-xl border border-border/60 bg-surface/40 p-5">
              <h3 className="text-sm font-semibold text-foreground">
                Regime prediction accuracy
              </h3>
              <p className="mt-2 text-xs text-muted-foreground">
                {trackingSince
                  ? `Tracking since ${trackingSince}`
                  : "Tracking starts when your first note is published."}
              </p>
              <p className="mt-3 text-lg font-semibold text-foreground">
                {notes.length} predictions published
              </p>
              <p className="mt-2 text-xs text-muted-foreground">
                Performance data builds over 30 days of publishing — we show
                honest counts, not inflated numbers.
              </p>
            </div>

            <div className="rounded-xl border border-primary/30 bg-primary/5 p-5">
              <h3 className="text-sm font-semibold text-foreground">
                Subscribe to research
              </h3>
              <ResearchSubscribeForm />
            </div>
          </aside>
        </div>
      </div>
    </div>
  );
}
