"""
pr_creator.py — Open GitHub PRs for agent-detected fixes using PyGithub.

PRs target `develop` branch (not main).
Labels: "agent-fix" + severity label.
Assignee: GITHUB_ASSIGNEE env var.
"""

import logging
import os
import re
import textwrap
from datetime import datetime, UTC

from github import Auth, Github, GithubException

log = logging.getLogger("neufin-agent.pr_creator")

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_REPO = os.getenv("GITHUB_REPO", "varunsrivastava/neufinapk1")
GITHUB_ASSIGNEE = os.getenv("GITHUB_ASSIGNEE", "varun")
PR_BASE_BRANCH = os.getenv("PR_BASE_BRANCH", "develop")

# Label colours (created on first use if missing)
_LABEL_COLORS: dict[str, str] = {
    "agent-fix": "0075ca",
    "severity:critical": "d73a4a",
    "severity:high": "e4e669",
    "severity:medium": "a2eeef",
    "severity:low": "cfd3d7",
}


def _slug(text: str, max_len: int = 30) -> str:
    """Convert text to a URL-safe slug."""
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s[:max_len]


def _pr_body(
    issue: dict,
    diff: str,
    root_cause: str,
    test_cmd: str,
    risk: str,
    requires_human: bool,
) -> str:
    sev = issue.get("severity", "unknown")
    itype = issue.get("type", "unknown")
    file_path = issue.get("file", "unknown")
    line = issue.get("line", 0)
    message = issue.get("message", "")
    issue_id = issue.get("id", "unknown")
    ts = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    human_note = (
        "⚠️ **REQUIRES_HUMAN_REVIEW** — do not merge without manual verification."
        if requires_human
        else f"Risk assessed as **{risk}** — review diff before merging."
    )

    diff_block = f"```diff\n{diff}\n```" if diff else "_No diff generated — see issue details._"

    return textwrap.dedent(f"""\
        ## 🤖 Auto-detected Issue

        **Severity:** {sev}
        **Type:** {itype}
        **File:** `{file_path}:{line}`

        ## Root Cause
        {root_cause or "_Not determined_"}

        ## Fix Applied
        {diff_block}

        ## Verification
        Run: `{test_cmd or "see fix diff"}`

        ## Risk Assessment
        {human_note}

        ---
        *Generated by Neufin Code Health Agent at {ts}*
        *Issue ID: `{issue_id}`*
    """)


def _ensure_labels(repo) -> None:
    """Create missing labels — best-effort, never raises."""
    existing = {lb.name for lb in repo.get_labels()}
    for name, color in _LABEL_COLORS.items():
        if name not in existing:
            try:
                repo.create_label(name=name, color=color)
            except GithubException:
                pass  # race condition or permissions issue — ignore


async def create_fix_pr(
    issue_id: str,
    file_path: str,
    new_content: str,
    branch_name: str,
    title: str,
    body: str,
) -> str:
    """
    Compatibility shim used by fix_engine for review PRs with pre-built title/body.
    Delegates to open_issue_pr with minimal wrapping.
    """
    if not GITHUB_TOKEN:
        log.warning({"action": "pr_skip", "reason": "GITHUB_TOKEN not set"})
        return ""

    issue_dict = {"id": issue_id, "file": file_path, "severity": "high",
                  "type": "unknown", "line": 0, "message": title}
    return await open_issue_pr(
        issue=issue_dict,
        diff="",
        root_cause=body,
        test_cmd="",
        risk="medium",
        requires_human=True,
        _override_title=title,
        _override_body=body,
        _override_branch=branch_name,
    )


async def open_issue_pr(
    issue: dict,
    diff: str,
    root_cause: str,
    test_cmd: str,
    risk: str,
    requires_human: bool,
    _override_title: str = "",
    _override_body: str = "",
    _override_branch: str = "",
) -> str:
    """
    Create a GitHub PR for an agent-detected issue.

    Returns the PR HTML URL, or "" if GitHub is not configured.
    """
    if not GITHUB_TOKEN:
        log.warning({"action": "pr_skip", "reason": "GITHUB_TOKEN not set"})
        return ""

    sev = issue.get("severity", "medium")
    issue_id = issue.get("id", "unknown")
    short_msg = issue.get("message", "")[:40]

    branch = _override_branch or f"agent/fix-{issue_id[:8]}-{_slug(short_msg)}"
    title = _override_title or f"[Agent] {sev.upper()}: {short_msg}"
    body = _override_body or _pr_body(issue, diff, root_cause, test_cmd, risk, requires_human)

    try:
        gh = Github(auth=Auth.Token(GITHUB_TOKEN))
        repo = gh.get_repo(GITHUB_REPO)

        # Resolve base branch (fall back to default if develop doesn't exist)
        try:
            base_ref = repo.get_branch(PR_BASE_BRANCH)
            base_sha = base_ref.commit.sha
            base_branch = PR_BASE_BRANCH
        except GithubException:
            base_branch = repo.default_branch
            base_sha = repo.get_branch(base_branch).commit.sha
            log.warning({
                "action": "pr_base_fallback",
                "wanted": PR_BASE_BRANCH,
                "using": base_branch,
            })

        # Create branch (ignore if already exists)
        try:
            repo.create_git_ref(ref=f"refs/heads/{branch}", sha=base_sha)
        except GithubException as exc:
            if exc.status != 422:
                raise

        # Commit diff as a placeholder file if new_content is empty
        # (for review-only PRs, we put the diff in the PR body — no file change needed)
        # If new_content is provided, update the actual file.
        if new_content and issue.get("file"):
            file_path = issue["file"]
            try:
                existing = repo.get_contents(file_path, ref=branch)
                repo.update_file(
                    path=file_path,
                    message=f"fix(agent): {issue_id[:8]} {short_msg} [auto]",
                    content=new_content,
                    sha=existing.sha,
                    branch=branch,
                )
            except GithubException:
                repo.create_file(
                    path=file_path,
                    message=f"fix(agent): {issue_id[:8]} {short_msg} [auto]",
                    content=new_content,
                    branch=branch,
                )

        # Ensure labels exist
        _ensure_labels(repo)

        # Create PR
        pr = repo.create_pull(
            title=title,
            body=body,
            head=branch,
            base=base_branch,
            draft=requires_human,  # draft if human review required
        )

        # Apply labels
        labels = ["agent-fix", f"severity:{sev}"]
        pr.add_to_labels(*labels)

        # Assign reviewer
        if GITHUB_ASSIGNEE:
            try:
                pr.add_to_assignees(GITHUB_ASSIGNEE)
            except GithubException:
                log.warning({"action": "pr_assign_failed", "assignee": GITHUB_ASSIGNEE})

        pr_url = pr.html_url
        log.info({
            "action": "pr_created",
            "url": pr_url,
            "issue_id": issue_id,
            "branch": branch,
            "draft": requires_human,
        })
        return pr_url

    except GithubException as exc:
        log.error({"action": "pr_error", "issue_id": issue_id, "status": exc.status, "data": exc.data})
        return ""
    except Exception as exc:
        log.error({"action": "pr_error", "issue_id": issue_id, "error": str(exc)})
        return ""
